export const CONSTANTS = {
  ENCRYPTED_PASSWORD_LENGTH: 60,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 30,
  MIN_DESCRIPTION_WORDS: 30,
  MAX_DESCRIPTION_WORDS: 150,
  MAX_IMAGE_SIZE: 5*1024*1024,
  ACCEPTED_IMAGE_TYPES: ["image/jpeg", "image/jpg", "image/png", "image/webp"],
  POSTS_PER_SCROLL: 7,
  COMMENTS_PER_SCROLL: 7,
};
